SneakerPalace/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.views.static import serve
import os

import xadmin

from users.views import LoginView, RegisterView, UserCenterView, ForgetView, ResetView, ModifyPwdView, IndexView, \
    SearchView, LogoutView, ContactView
from SneakerPalace.settings import MEDIA_ROOT, STATIC_ROOT


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),

    # 富文本相关url
    url(r'^ueditor/', include(('DjangoUeditor.urls', 'ueditor'), namespace='ueditor')),

    url(r'^$', IndexView.as_view(), name="index"),
    url(r'^user_center/$', UserCenterView.as_view(), name="user_center"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^forget/$', ForgetView.as_view(), name="forget"),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset"),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^search/$', SearchView.as_view(), name="search"),
    url(r'^contact/$', ContactView.as_view(), name="contact"),

    url(r'^products/', include(('sneakers.urls', 'sneakers'), namespace="products")),
    url(r'^blog/', include(('blog.urls', 'blog'), namespace="blog")),

    # 配置上传文件的访问处理函数
    url(r'media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),

    url(r'static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),
]
handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/blog/urls.py
from django.conf.urls import url, include
from blog.views import BlogListView, BlogDetailView

urlpatterns = [
    url(r'^list/$', BlogListView.as_view(), name="blog_list"),
    url(r'^detail/(?P<blog_id>.*)/$', BlogDetailView.as_view(), name="blog_detail"),
]

apps/sneakers/urls.py
from django.conf.urls import url, include
from sneakers.views import ProductsListView, ProductDetailView, AddFavView, RemoveFavView, ComparisonPriceView

urlpatterns = [
    url(r'^list/$', ProductsListView.as_view(), name="products_list"),
    url(r'^detail/(?P<style>.*)/$', ProductDetailView.as_view(), name="products_detail"),
    url(r'^comparison/$', ComparisonPriceView.as_view(), name="products_comparison"),

    # 收藏
    url(r'^add_fav/$', AddFavView.as_view(), name="add_fav"),
    url(r'^remove_fav/$', RemoveFavView.as_view(), name="remove_fav"),
]

extra_apps/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/sneakers/models.py
from django.db import models

from datetime import datetime


# Create your models here.


class Sneakers(models.Model):
    id_in_du = models.IntegerField(primary_key=True, verbose_name="毒产品ID")
    brand = models.CharField(max_length=10,
                             choices=(("Jordan", "Jordan"), ("Nike", "Nike"), ("Adidas", "Adidas"), ("Yeezy", "Yeezy")),
                             default="Jordan", verbose_name="球鞋品牌")
    name = models.CharField(max_length=100, default="", verbose_name="球鞋名称")
    style = models.CharField(max_length=50, default="", verbose_name="球鞋货号")
    image = models.ImageField(upload_to="sneakers/%Y/%m", verbose_name="球鞋图片", max_length=100)
    sold_nums = models.IntegerField(default=0, verbose_name="销售量")
    retail_price = models.IntegerField(default=0, verbose_name="发售价")
    retail_date = models.CharField(max_length=50, default="", verbose_name="发售日期")
    click_nums = models.IntegerField(default=0, verbose_name="点击数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏数")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "球鞋信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Price(models.Model):
    id_in_du = models.ForeignKey(Sneakers, verbose_name="毒产品ID", on_delete=models.CASCADE)
    style = models.CharField(max_length=50, default="", verbose_name="球鞋货号")
    size = models.FloatField(default=0, verbose_name="尺码")
    price = models.IntegerField(default=0, verbose_name="价格")

    class Meta:
        verbose_name = "球鞋价格"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.size

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass

def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)

def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):
    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user, 
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user
        
        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>激活链接失效</title>
</head>
<body>
<p>激活链接失效</p>
</body>
</html>

templates/base.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/meanmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'css/default.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    {% block custom_css %}{% endblock %}
</head>
<body>


<!-- preloader -->
<div id="preloader">
    <div class="preloader">
        <span></span>
        <span></span>
    </div>
</div>
<!-- preloader end  -->

<!-- header start -->
<header>
    <div id="header-sticky" class="header-area box-90">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-xl-2 col-lg-6 col-md-6 col-7 col-sm-5 d-flex align-items-center pos-relative">
                    <div class="basic-bar cat-toggle">
                        <span class="bar1"></span>
                        <span class="bar2"></span>
                        <span class="bar3"></span>
                    </div>
                    <div class="logo">
                        <a href="{% url 'index' %}"><img src="{% static 'img/logo/logo.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-xl-8 col-lg-6 col-md-8 col-8 d-none d-xl-block">
                    <div class="main-menu text-center">
                        <nav id="mobile-menu">
                            <ul>
                                <li>
                                    <a href="{% url 'index' %}">首页</a>
                                </li>
                                <li>
                                    <a href="{% url 'products:products_list' %}">商品 </a>
                                </li>
                                <li>
                                    <a href="{% url 'blog:blog_list' %}">资讯</a>
                                </li>
                                <li>
                                    <a href="{% url 'products:products_comparison' %}">球鞋比价</a>
                                </li>
                                <li>
                                    <a href="{% url 'contact' %}">联系我们</a>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-xl-2 col-lg-6 col-md-6 col-5 col-sm-7 pl-0">
                    <div class="header-right f-right">
                        <ul>
                            <li class="search-btn">
                                <a class="search-btn nav-search search-trigger" href="#" style=""><i
                                        class="fas fa-search"></i></a>
                            </li>
                            {% if request.user.is_authenticated %}
                                <li class="login-btn"><a href="{% url 'user_center' %}"><i
                                        class="far fa-user"></i></a>
                                    <ul class="usercenter">
                                        <li>
                                            <div class="quit">
                                                <a class="red-color" href="{% url 'logout' %}">退出登录</a>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            {% else %}
                                <li class="login-btn"><a href="{% url 'login' %}"><i
                                    class="far fa-user"></i></a>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <div class="col-12 d-xl-none">
                    <div class="mobile-menu"></div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- header end -->
{% block content %}
{% endblock %}
<!-- footer start -->
<footer>
    <div class="copyright-area box-105">
        <div class="container-fluid">
            <div class="copyright-border pt-30 pb-30">
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6">
                        <div class="copyright text-center text-md-left">
                            <p>本站数据来自于 <a href="http://www.flightclub.cn/">flightclub中文站</a> 、<a
                                    href="https://www.poizon.com/">得物APP</a>，只用于学习交流，无任何商业目的。如有侵权，请联系我删除。</p>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6">
                        <div class="footer-icon text-center text-md-right ">
                            <p>鞋宫-球鞋潮流玩家交流地</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- footer end -->

<!-- Fullscreen search -->
<div class="search-wrap">
    <div class="search-inner">
        <i class="fas fa-times search-close" id="search-close"></i>
        <div class="search-cell">
            <div class="search-field-holder">
                <input type="search" name="keywords" id="search_keywords" class="main-search-input"
                       placeholder="Search Entire Store...">
            </div>
        </div>
    </div>
</div> <!-- end fullscreen search -->


<!-- JS here -->
<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'js/one-page-nav-min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/jquery.meanmenu.min.js' %}"></script>
<script src="{% static 'js/ajax-form.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
<script src="{% static 'js/jquery.final-countdown.min.js' %}"></script>
<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/plugins.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/jquery.lazyload.js' %}"></script>

<script type="text/javascript">

    $('#search_keywords').keydown(function (event) {

        var keywords = $('#search_keywords').val();

        if (event.keyCode == 13) {
            url = '{% url "search" %}';
            window.location.href = url + '?keywords=' + keywords;
        }});
</script>

{% block custom_js %}
{% endblock %}

templates/blog-details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} 鞋宫-潮流资讯 {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
{% endblock %}

{% block content %}
    <main>

        <!-- breadcrumb-area-start -->
        <section class="breadcrumb-area">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                    </div>
                </div>
            </div>
        </section>
        <!-- breadcrumb-area-end -->

        <!-- blog-area start -->
        <div class="blog-area pt-100 pb-60">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <article class="postbox post format-image mb-40">
                            <div class="postbox__text bg-none">
                                <div class="post-meta mb-15">
                                    <span><i class="far fa-calendar-check"></i> {{ blog_info.release_time }} </span>
                                    <span><i class="far fa-comments"></i> 浏览次数 {{ blog_info.click_nums }} </span>
                                </div>
                                <h3 class="blog-title">
                                    {{ blog_info.title }}
                                </h3>
                                <div class="post-text mb-20">
                                    {% autoescape off %}
                                        {{ blog_info.content }}
                                    {% endautoescape %}
                                </div>
{#                                <div class="row mt-50">#}
{#                                    <div class="col-xl-8 col-lg-8 col-md-8 mb-15">#}
{#                                        <div class="blog-post-tag">#}
{#                                            <span>Releted Tags</span>#}
{#                                            <a href="#">organic</a>#}
{#                                            <a href="#">Foods</a>#}
{#                                            <a href="#">tasty</a>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="col-xl-4 col-lg-4 col-md-4 mb-15">#}
{#                                        <div class="blog-share-icon text-left text-md-right">#}
{#                                            <span>Share: </span>#}
{#                                            <a href="#"><i class="fab fa-facebook-f"></i></a>#}
{#                                            <a href="#"><i class="fab fa-twitter"></i></a>#}
{#                                            <a href="#"><i class="fab fa-instagram"></i></a>#}
{#                                            <a href="#"><i class="fab fa-google-plus-g"></i></a>#}
{#                                            <a href="#"><i class="fab fa-vimeo-v"></i></a>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </div>#}
                            </div>
                        </article>
                    </div>
                    <div class="col-lg-4">
                        <div class="widget mb-40">
                            <div class="widget-title-box mb-30">
                                <span class="animate-border"></span>
                                <h3 class="widget-title">其他热门资讯</h3>
                            </div>
                            <ul class="recent-posts">
                                {% for blog in other_blog %}
                                    <li>
                                        <div class="widget-posts-image">
                                            <a href="{% url 'blog:blog_detail' blog.id %}"><img src="{{ MEDIA_URL }}{{ blog.image }}" alt=""></a>
                                        </div>
                                        <div class="widget-posts-body">
                                            <h6 class="widget-posts-title"><a href="{% url 'blog:blog_detail' blog.id %}">{{ blog.title }}</a></h6>
                                            <div class="widget-posts-meta">{{ blog.release_time }}</div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- blog-area end -->


    </main>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" charset="utf-8">
        $(function () {
            $("img.lazy").lazyload({effect: "fadeIn"});
        });
    </script>
{% endblock %}

templates/user_center.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} 鞋宫-个人中心 {% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
{% endblock %}

{% block content %}
    <body>
    <section class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="breadcrumb-text text-center">
                        <h1>个人中心</h1>
                        <h2>{{ user_name }}</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="cart-area pt-100 pb-100">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <form action="#">
                        <div class="table-content table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th class="product-thumbnail">图片</th>
                                    <th class="cart-product-name">名称</th>
                                    <th class="product-price">发售价</th>
                                    <th class="product-remove">取消收藏</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for sneaker in sneakers_list %}
                                    <tr>
                                        <td class="product-thumbnail"><a
                                                href="{% url 'products:products_detail' sneaker.style %}"><img
                                                src="{{ MEDIA_URL }}{{ sneaker.image }}"
                                                alt=""></a></td>
                                        <td class="product-name"><a
                                                href="{% url 'products:products_detail' sneaker.style %}">{{ sneaker.name }}</a>
                                        </td>
                                        <td class="product-price"><span class="amount">{{ sneaker.retail_price }}</span>
                                        </td>
                                        <td class="product-remove"><a onclick="remove_fav({{ sneaker.id_in_du }})"><i
                                                class="fa fa-times"></i></a></td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    </body>
{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        function remove_fav(fav_id) {
            $.ajax({
                cache: false,
                type: 'POST',
                url: "{% url 'products:remove_fav' %}",
                data: {'fav_id': fav_id},
                async: true,
                beforeSend: function (xhr, settings) {
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                },
                success: function () {
                    window.location.href = "{% url 'user_center' %}"
                }
            });
        }
    </script>
{% endblock %}